const path = require('path')
console.log(path.resolve('./foo', 'bar', 'baz/asdf', 'quux', '..'))
console.log(path.resolve('foo', 'bar', 'baz/asdf', 'quux', '..'))
console.log(path.join('foo', 'bar', 'baz/asdf', 'quux', '..'))
console.log(path.join('./foo', 'bar', 'baz/asdf', 'quux', '..'))
// console.log(path.join('foo', 'bar', 'baz/asdf', 'quux', '..'))
// console.log(path.resolve(__dirname))
